openapi: 3.0.3
info:
  title: Users API
  description: |
    A collection of operations managing users
  contact:
    name: George K
    email: georgek@nonamesecurity.com
  version: v1

servers:
  - # local server
    url: https://localhost:58443/api/v1
    description: |
      Local server
  - # Net accessible
    url: https://<aws-host>:5843/api/v1
    description: |
      Net accessible server
      
tags:
  - name: Users
  
paths:

  /users:

    post:
      description: |
        Anyone can self-register with role user provided
        there is no authorization header present.
        Admin's can register other users with any role.
        Operators can register only normal users
      tags:
        - Users
      security: 
        - nonameJWT: []
        - {}
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: |
            Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success

  /tokens:
  
    post:
      tags:
        - Users
      security:
        - basicAuth: []
      responses:
        "201":
          description: |
            Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

components:

  securitySchemes: 
    basicAuth:
      type: http
      scheme: Basic
    nonameJWT: 
      type: http
      scheme: Bearer

  schemas:
    User:
      type: object
      required:
        - username
        - password
        - email
        - app
      properties:
        id:
          type: integer
          format: int32
          example: 1
        username:
          type: string
          example: "John"
        password:
          type: string
          example: "Doe"
        email:
          type: string
          example: "John.Doe@acme.com"
        role:
          description: |
            Role is optional, use the default value.
          type: string
          enum:
            - admin
            - oper
            - user
          default: user
          example: user
        app:
          type: string
          example: Flights App
